# Build stage
FROM maven:3.8.5-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

# Run stage
FROM openjdk:17-slim
COPY --from=build /target/lifethings_runnable.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
